### PR TITLE
Activity13

### PR DESCRIPTION
**Pull request by ChadOlsen**
Please review activity 13

### CODE REVIEW

**Comment by ghost** [comment]
@ChadOlsen - First thing - all pull requests base branch should be off of develop and not master.

**Review by ghost — CHANGES_REQUESTED** [review]
AccountManager.dat and Catalogue.dat should be removed from the repo.

Remove the out/ folder from the repo.

**Comment by ghost** [comment]
@ChadOlsen  Remove all .iml files from the repo

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Please merge this branch into develop through the command line. @ChadOlsen ensure that only a single commit is merged

**Comment by ChadOlsen** [comment]
Merged to develop manually through the command line

**Pull request closed without merging**
